//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 10:59:25 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.moran.com/home/service/soap/stubs")
package com.moran.home.service.soap.stubs;
